name: Build Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Compile firmware
      run: |
        chmod +x compile-with-docker.sh
        ./compile-with-docker.sh

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v7
      with:
        name: firmware-artifact
        path: build/Custom/f4hwn.custom.bin
